### PR TITLE
test apply

### PR DESCRIPTION
**Pull request by adaam**

### CODE REVIEW

**Comment by adaam** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Exporting secrets

Acquiring state lock. This may take a few moments...

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.hub.module.vpc.aws_internet_gateway.this[0] will be created
+ resource "aws_internet_gateway" "this" {
      + arn      = (known after apply)
      + id       = (known after apply)
      + owner_id = (known after apply)
      + tags     = {
          + "Name" = "testVPC"
        }
      + tags_all = {
          + "Name" = "testVPC"
        }
      + vpc_id   = (known after apply)
    }

  # module.hub.module.vpc.aws_route.public_internet_gateway[0] will be created
+ resource "aws_route" "public_internet_gateway" {
      + destination_cidr_block = "0.0.0.0/0"
      + gateway_id             = (known after apply)
      + id                     = (known after apply)
      + instance_id            = (known after apply)
      + instance_owner_id      = (known after apply)
      + network_interface_id   = (known after apply)
      + origin                 = (known after apply)
      + route_table_id         = (known after apply)
      + state                  = (known after apply)

      + timeouts {
          + create = "5m"
        }
    }

  # module.hub.module.vpc.aws_route_table.private[0] will be created
+ resource "aws_route_table" "private" {
      + arn              = (known after apply)
      + id               = (known after apply)
      + owner_id         = (known after apply)
      + propagating_vgws = (known after apply)
      + route            = (known after apply)
      + tags             = {
          + "Name" = "testVPC-private"
        }
      + tags_all         = {
          + "Name" = "testVPC-private"
        }
      + vpc_id           = (known after apply)
    }

  # module.hub.module.vpc.aws_route_table.public[0] will be created
+ resource "aws_route_table" "public" {
      + arn              = (known after apply)
      + id               = (known after apply)
      + owner_id         = (known after apply)
      + propagating_vgws = (known after apply)
      + route            = (known after apply)
      + tags             = {
          + "Name" = "testVPC-public"
        }
      + tags_all         = {
          + "Name" = "testVPC-public"
        }
      + vpc_id           = (known after apply)
    }

  # module.hub.module.vpc.aws_route_table_association.private[0] will be created
+ resource "aws_route_table_association" "private" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # module.hub.module.vpc.aws_route_table_association.private[1] will be created
+ resource "aws_route_table_association" "private" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # module.hub.module.vpc.aws_route_table_association.public[0] will be created
+ resource "aws_route_table_association" "public" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # module.hub.module.vpc.aws_route_table_association.public[1] will be created
+ resource "aws_route_table_association" "public" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # module.hub.module.vpc.aws_subnet.private[0] will be created
+ resource "aws_subnet" "private" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-west-2a"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.199.10.0/24"
      + id                              = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = false
      + owner_id                        = (known after apply)
      + tags                            = {
          + "Name" = "testVPC-private-us-west-2a"
        }
      + tags_all                        = {
          + "Name" = "testVPC-private-us-west-2a"
        }
      + vpc_id                          = (known after apply)
    }

  # module.hub.module.vpc.aws_subnet.private[1] will be created
+ resource "aws_subnet" "private" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-west-2b"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.199.11.0/24"
      + id                              = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = false
      + owner_id                        = (known after apply)
      + tags                            = {
          + "Name" = "testVPC-private-us-west-2b"
        }
      + tags_all                        = {
          + "Name" = "testVPC-private-us-west-2b"
        }
      + vpc_id                          = (known after apply)
    }

  # module.hub.module.vpc.aws_subnet.public[0] will be created
+ resource "aws_subnet" "public" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-west-2a"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.199.20.0/24"
      + id                              = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = true
      + owner_id                        = (known after apply)
      + tags                            = {
          + "Name" = "testVPC-public-us-west-2a"
        }
      + tags_all                        = {
          + "Name" = "testVPC-public-us-west-2a"
        }
      + vpc_id                          = (known after apply)
    }

  # module.hub.module.vpc.aws_subnet.public[1] will be created
+ resource "aws_subnet" "public" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-west-2b"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "10.199.21.0/24"
      + id                              = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = true
      + owner_id                        = (known after apply)
      + tags                            = {
          + "Name" = "testVPC-public-us-west-2b"
        }
      + tags_all                        = {
          + "Name" = "testVPC-public-us-west-2b"
        }
      + vpc_id                          = (known after apply)
    }

  # module.hub.module.vpc.aws_vpc.this[0] will be created
+ resource "aws_vpc" "this" {
      + arn                              = (known after apply)
      + assign_generated_ipv6_cidr_block = false
      + cidr_block                       = "10.199.0.0/16"
      + default_network_acl_id           = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_group_id        = (known after apply)
      + dhcp_options_id                  = (known after apply)
      + enable_classiclink               = (known after apply)
      + enable_classiclink_dns_support   = (known after apply)
      + enable_dns_hostnames             = true
      + enable_dns_support               = true
      + id                               = (known after apply)
      + instance_tenancy                 = "default"
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      + main_route_table_id              = (known after apply)
      + owner_id                         = (known after apply)
      + tags                             = {
          + "Name" = "testVPC"
        }
      + tags_all                         = {
          + "Name" = "testVPC"
        }
    }

Plan: 13 to add, 0 to change, 0 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http:/lock?id=adaam%252Fatlantis-example%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 13 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by adaam** [comment]
atlantis apply

**Comment by adaam** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by lydia-ai-adam — APPROVED** [review]
lg

**Comment by lydia-ai-adam** [comment]
atlantis apply

**Comment by adaam** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Acquiring state lock. This may take a few moments...
module.hub.module.vpc.aws_vpc.this[0]: Creating...
module.hub.module.vpc.aws_vpc.this[0]: Still creating... [10s elapsed]
module.hub.module.vpc.aws_vpc.this[0]: Creation complete after 16s [id=vpc-075bd837aa7dbcf27]
module.hub.module.vpc.aws_subnet.public[1]: Creating...
module.hub.module.vpc.aws_route_table.public[0]: Creating...
module.hub.module.vpc.aws_route_table.private[0]: Creating...
module.hub.module.vpc.aws_internet_gateway.this[0]: Creating...
module.hub.module.vpc.aws_subnet.private[0]: Creating...
module.hub.module.vpc.aws_subnet.public[0]: Creating...
module.hub.module.vpc.aws_subnet.private[1]: Creating...
module.hub.module.vpc.aws_route_table.public[0]: Creation complete after 2s [id=rtb-09127a85990b0e331]
module.hub.module.vpc.aws_route_table.private[0]: Creation complete after 2s [id=rtb-0ae08ace7527726e8]
module.hub.module.vpc.aws_subnet.private[1]: Creation complete after 2s [id=subnet-053867a4ee9c1fc99]
module.hub.module.vpc.aws_subnet.private[0]: Creation complete after 2s [id=subnet-03f977cb60517b9a5]
module.hub.module.vpc.aws_route_table_association.private[0]: Creating...
module.hub.module.vpc.aws_route_table_association.private[1]: Creating...
module.hub.module.vpc.aws_internet_gateway.this[0]: Creation complete after 3s [id=igw-003fb3800b9c955bc]
module.hub.module.vpc.aws_route.public_internet_gateway[0]: Creating...
module.hub.module.vpc.aws_route_table_association.private[1]: Creation complete after 2s [id=rtbassoc-09fcef57e716d4b30]
module.hub.module.vpc.aws_route_table_association.private[0]: Creation complete after 2s [id=rtbassoc-0399ef66b27b7bb7f]
module.hub.module.vpc.aws_route.public_internet_gateway[0]: Creation complete after 2s [id=r-rtb-09127a85990b0e3311080289494]
module.hub.module.vpc.aws_subnet.public[1]: Still creating... [10s elapsed]
module.hub.module.vpc.aws_subnet.public[0]: Still creating... [10s elapsed]
module.hub.module.vpc.aws_subnet.public[0]: Creation complete after 13s [id=subnet-074df15e158d50eec]
module.hub.module.vpc.aws_subnet.public[1]: Creation complete after 13s [id=subnet-0c98be8921e91c284]
module.hub.module.vpc.aws_route_table_association.public[0]: Creating...
module.hub.module.vpc.aws_route_table_association.public[1]: Creating...
module.hub.module.vpc.aws_route_table_association.public[1]: Creation complete after 2s [id=rtbassoc-06ba32f1494ebf8c1]
module.hub.module.vpc.aws_route_table_association.public[0]: Creation complete after 2s [id=rtbassoc-0f2fc9acc30665b86]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 13 added, 0 changed, 0 destroyed.

```
</details>

**Comment by adaam** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
